### PR TITLE
Added new rollup operations

### PR DESCRIPTION
**Pull request by afawcett**
Count Distinct, Concatenate, Concatenate Distinct, First, Last (see
http://andyinthecloud.com/2015/02/16/declarative-lookup-rollup-summaries
-tool-dlrs-spring15-release/ for more details).

### CODE REVIEW

**Comment by afawcett** [comment]
This [link](https://github.com/abhinavguptas/Salesforce-Lookup-Rollup-Summaries/pull/14/files?w=1) will do the diff and remove white space, should make it clearer. Also see my [blog](http://andyinthecloud.com/2015/02/16/declarative-lookup-rollup-summaries-tool-dlrs-spring15-release) on the new operations.

**Comment by afawcett** [comment]
Sorry its taken a while to contribute back my changes btw!

**Comment by afawcett** [comment]
Any thoughts on merging this? There is quite a bit of working going on in DLRS at present, i'm keen to ensure that any work that benefits this fine library is paid back.

**Comment by abhinavguptas** [comment]
Sorry for delay @afawcett - happy to discuss any more planned features.

**Comment by afawcett** [comment]
Ah excellent, thanks for this! I'll have to compare the current LREngine.cls in DLRS now, i'm sure it has had more improvements since this PR. Thanks again!

**Pull request merged**
